# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'QuizMasterGame' do
pod 'Parse', '~> 1.4.2'
end

target 'QuizMasterGameTests' do

end

