# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'QuizMasterGame' do
pod 'Parse', '~> 1.4.2'
pod 'Facebook-iOS-SDK', '~> 3.20.0'
end

target 'QuizMasterGameTests' do

end

